jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "11"
      script: npm install
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
notifications:
  email:
    recipients:
      - 710101991@qq.com
    on_success: always # default: change
    on_failure: always # default: always